server.port: 8080
server.error.include-message: always

spring.application.name: user-composite

app:
  auth-server: auth-server

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999

springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: dev.kalbarczyk.microservices.composite.user
  pathsToMatch: /**
  cache.disabled: true

  swagger-ui:
    oauth2-redirect-url: /swagger-ui/oauth2-redirect.html
    oauth:
      clientId: writer
      clientSecret: secret-writer
      useBasicAuthenticationWithAccessCodeGrant: true
  oAuthFlow:
    authorizationUrl: https://localhost:8443/oauth2/authorize
    tokenUrl: https://localhost:8443/oauth2/token

server.forward-headers-strategy: framework

api:
  common:
    version: 1.0.0
    title: User Composite Service API
    description: API for the User Composite Service
    termsOfService: example.com/terms
    license: Example License
    licenseUrl: example.com/license
    externalDocDesc: Example External Docs
    externalDocUrl: example.com/repository
    contact:
      name: Oskar Kalbarczyk
      url: https://kalbarczyk.dev
      email: example@email.com

  responseCodes:
    ok.description: OK
    badRequest.description: Bad Request, invalid format of the request. See response message for more information
    notFound.description: Not found, the specified id does not exist
    unprocessableEntity.description: Unprocessable entity, input parameters caused the processing to fail. See response message for more information

  user-composite:

    getUserProfile:
      description: Gets the user and profile information.
      notes: |
        # Normal response
        If the requested userId is found the method will return information regarding:
        1. User
        2. Profile

        # Expected partial and error responses
        1. If no user information is found, a **404 - Not Found** error will be returned

    createUser:
      description: Creates a new user and minimal profile
      notes: |
        # Normal response
        The  createUser information posted to the API will be split up and stored as separate user and profile entities.

        # Expected error responses
        1. If a user with the same email as specified in the posted information already exists,
           an **422 - Unprocessable Entity** error with a "duplicate key" error message will be returned

    updateProfile:
      description: Updates the profile information for the given userId
      notes: |
        # Normal response
        The profile information posted to the API will update the existing profile entity related to the specified userId.

        # Expected error responses
        1. If no user information is found for the specified userId, a **404 - Not Found** error will be returned

    deleteUser:
      description:  Deletes a user and associated profile
      notes: |
        # Normal response
        Entities for user and profile related to the specified userId will be deleted.
        The implementation of the delete method is idempotent, i.e. it can be called several times with the same response.

        This means that a delete request of a non-existing product will return **200 Ok**.


eureka:
  client:
    serviceUrl:
      defaultZone: http://u:p@eureka:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    users-out-0:
      destination: users
      producer:
        required-groups: auditGroup
    profiles-out-0:
      destination: profiles
      producer:
        required-groups: auditGroup

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    dev.kalbarczyk: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
