server.port: 8080
server.error.include-message: always

spring.application.name: user-composite

app:
  auth-server: auth-server

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.auth-server}:9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://u:p@eureka:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    users-out-0:
      destination: users
      producer:
        required-groups: auditGroup
    profiles-out-0:
      destination: profiles
      producer:
        required-groups: auditGroup

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest

logging:
  level:
    root: INFO
    dev.kalbarczyk: DEBUG
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
