server.port: 7001

app:
  user-service:
    host: localhost
    port: 7002
  profile-service:
    host: localhost
    port: 7003


server.error.include-message: always
logging:
  level:
    root: INFO
    dev.kalbarczyk: DEBUG

---
spring.config.activate.on-profile: docker

server.port: 8080

app:
  user-service:
    host: user
    port: 8080
  profile-service:
    host: profile
    port: 8080
