app:
  eureka-username: u
  eureka-password: p
  eureka-server: eureka
  auth-server: auth-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://u:p@eureka:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.rabbitmq:
  host: rabbitmq
  port: 5672
  username: guest
  password: guest

spring:
  cloud:
    stream:
      default-binder: rabbit
      binders:
        rabbit:
          type: rabbit


# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"





