services:
    user:
        build: microservices/user-service
        mem_limit: 512m
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    profile:
        build: microservices/profile-service
        mem_limit: 512m
        environment:
            - SPRING_PROFILES_ACTIVE=docker

    user-composite:
        build: microservices/user-composite-service
        mem_limit: 512m
        ports:
            - "8080:8080"
        environment:
            - SPRING_PROFILES_ACTIVE=docker