pluginManagement {
    repositories {
        gradlePluginPortal()
    }
}

include ':api'
include ':util'

include ':microservices:user-composite-service'
include ':microservices:user-service'
include ':microservices:profile-service'
include ':microservices:workout-service'
include ':spring-cloud:eureka-server'
include ':spring-cloud:gateway'
include ':spring-cloud:authorization-server'