spring:
  application:
    name: exercise-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/thesis?createDatabaseIfNotExist=true
    username: root
    password: learnSpring
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


