spring:
  application:
    name: exercise-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://mysql:3306/thesis?createDatabaseIfNotExist=true
    username: root
    password: root
    hikari:
      connection-timeout: 60000
      initialization-fail-timeout: 60000
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


