server.port: 70011
server.error.include-message: always

spring.data.mongodb:
  host: localhost
  port: 27017
  database: mongo-db
  username: root
  password: pwd


logging:
  level:
    root: INFO
    dev.kalbarczyk: DEBUG


---
spring.config.activate.on-profile: docker

server.port: 8080

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: mongo-db
      username: root
      password: pwd
      authentication-database: admin

